-- create-tables.sql
-- NOTE: This file has been intentionally cleared. The project assumes the
-- target database and tables already exist; creating tables in local dev
-- may cause schema drift. Keep DDL out of the repo unless you want to
-- explicitly manage local test databases.
