name: Azure Static Web Apps & Azure Functions CI/CD

on:
  push:
    branches:
      - 2Branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - 2Branch

jobs:
  frontend_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # フロントエンドのビルド
      - name: Build frontend
        run: |
          cd ./src
          npm install
          npm run build
      # SWAへのデプロイ
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_COAST_088BD3400 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src"
          output_location: "build"
          api_location: "" # Functionsは別リソースなので空欄

  backend_deploy_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show .NET SDKs on runner
        run: dotnet --list-sdks
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.413'
      - name: Restore NuGet packages
        run: dotnet restore ./api/DlpFunctions.csproj
      - name: Build Azure Functions
        run: dotnet build ./api/DlpFunctions.csproj --configuration Release --output ./output
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: dlp-servey-fc-bhcyaqe0e6c6andct
          package: ./output
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
